--- !DirTarget
pathToTemplateModelsDirectory: /Users/giovaniguizzo/NetBeansProjects/OPLA-Patterns/config/
directoryToSaveModels: manipulation/
directoryToExportModels: output/TestePatterns/
pathToProfile: /Users/giovaniguizzo/NetBeansProjects/OPLA-Patterns/config/smarty.profile.uml
pathToProfileConcern: /Users/giovaniguizzo/NetBeansProjects/OPLA-Patterns/config/perfilConcerns.profile.uml
