--- !DirTarget
pathToTemplateModelsDirectory: /home/giovaniguizzo/NetBeansProjects/OPLA-Patterns/config/
directoryToSaveModels: manipulation/
directoryToExportModels: output/TestePatterns/
pathToProfile: /home/giovaniguizzo/NetBeansProjects/OPLA-Patterns/AGMFinal/smarty.profile.uml
pathToProfileConcern: /home/giovaniguizzo/NetBeansProjects/OPLA-Patterns/AGMFinal/perfilConcerns.profile.uml
